{ name = "morello"
, dependencies =
  [ "barlow-lens"
  , "console"
  , "debug"
  , "effect"
  , "heterogeneous"
  , "heterogeneous-extrablatt"
  , "profunctor-lenses"
  , "psci-support"
  , "spec"
  , "spec-discovery"
  , "strings"
  , "validation"
  , "aff"
  , "arrays"
  , "either"
  , "foldable-traversable"
  , "integers"
  , "maybe"
  , "newtype"
  , "prelude"
  , "profunctor"
  , "record"
  , "tuples"
  , "typelevel-prelude"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
, license = "MIT-0"
, repository = "https://github.com/sigma-andex/purescript-morello.git"
}
